builders:
  i18nBuilder:
    import: 'package:i18n_code_gen/i18n_code_gen.dart'
    builder_factories: ['i18nBuilder']
    build_extensions:
      .json:
        - .dart
    build_to: source
    auto_apply: dependents